"""Portable comparisons against outputs captured from archived implementations.

The fixtures are historical reference data, not outputs regenerated by these tests.
No Git executable, source history, Census data, or training job is required.
"""

import hashlib
import json
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import pytest
import torch

from core.config import ScalingConfig
from core.datamodule import BinnedMaskedDataset
from core.models import TransformerModel

REFERENCE_DIR = Path(__file__).parent / "reference_data" / "training_behavior"
MANIFEST = json.loads((REFERENCE_DIR / "manifest.json").read_text())


@pytest.mark.parametrize("case", MANIFEST["cases"], ids=lambda case: case["id"])
def test_archived_training_reference(case):
    path = REFERENCE_DIR / case["file"]
    assert hashlib.sha256(path.read_bytes()).hexdigest() == case["sha256"]
    config = ScalingConfig(case["config"])
    with (
        np.load(path, allow_pickle=False) as reference,
        torch.random.fork_rng(devices=[]),
    ):
        model = TransformerModel(config).eval()
        model.load_state_dict(
            {
                key.removeprefix("state/"): torch.from_numpy(reference[key].copy())
                for key in reference.files
                if key.startswith("state/")
            },
            strict=True,
        )
        expr = torch.from_numpy(reference["input/expressions"])
        genes = torch.from_numpy(reference["input/genes"])
        mask = torch.from_numpy(reference["input/mask"])

        def matches(actual, expected):
            assert torch.isfinite(actual).all()
            torch.testing.assert_close(
                actual,
                torch.from_numpy(expected),
                rtol=MANIFEST["rtol"],
                atol=MANIFEST["atol"],
            )

        matches(model.get_encoder_output(genes, expr), reference["expected/encoder"])
        losses = model.step((expr, genes, mask, None), 0)["losses"]
        expected_loss_names = {
            key.removeprefix("loss/")
            for key in reference.files
            if key.startswith("loss/")
        }
        assert set(losses) == expected_loss_names
        for name, loss in losses.items():
            matches(loss, reference[f"loss/{name}"])
        sum(losses.values()).backward()
        actual_gradients = {
            name: param.grad
            for name, param in model.named_parameters()
            if param.grad is not None
        }
        expected_gradient_names = {
            key.removeprefix("gradient/")
            for key in reference.files
            if key.startswith("gradient/")
        }
        assert set(actual_gradients) == expected_gradient_names
        for name, gradient in actual_gradients.items():
            matches(gradient, reference[f"gradient/{name}"])

        if case["binned_dataset"]:
            obs = SimpleNamespace(
                dataset_id=["synthetic"], cell_type_ontology_term_id=["unknown"]
            )
            dataset = BinnedMaskedDataset(
                [(reference["dataset/input"].copy(), obs)], config, {"synthetic": 0}
            )
            rng_state = np.random.get_state()
            try:
                np.random.seed(MANIFEST["dataset_seed"])
                batch = next(iter(dataset))
            finally:
                np.random.set_state(rng_state)
            assert len(batch) == 6
            for index in (0, 1, 2, 4):
                torch.testing.assert_close(
                    batch[index],
                    torch.from_numpy(reference[f"dataset/output/{index}"]),
                    rtol=0,
                    atol=0,
                )
            assert batch[3] is None
            assert batch[5] == ["unknown"]
