#!/usr/bin/env python3
"""Regenerate the embedded Nature-style reference list from bibliography.bib."""
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent
BEGIN = "% BEGIN GENERATED BIBLIOGRAPHY"
END = "% END GENERATED BIBLIOGRAPHY"


def main():
    manuscript = ROOT / "manuscript.tex"
    source = manuscript.read_text()
    if source.count(BEGIN) != 1 or source.count(END) != 1:
        raise ValueError("Expected one pair of bibliography markers")
    before, rest = source.split(BEGIN)
    _, after = rest.split(END)
    text = re.sub(r"(?<!\\)%[^\n]*", "", before + after)
    citations = list(dict.fromkeys(
        key.strip()
        for group in re.findall(r"\\cite\w*\*?(?:\[[^\]]*\])*\{([^}]+)\}", text)
        for key in group.split(",")
    ))
    if not citations or any(not re.fullmatch(r"[\w:.-]+", key) for key in citations):
        raise ValueError("Missing or unsupported citation keys")
    with tempfile.TemporaryDirectory(prefix="nature-bibliography-") as directory:
        work = Path(directory)
        for filename in ("bibliography.bib", "sn-nature.bst"):
            shutil.copy2(ROOT / filename, work / filename)
        aux = "\\relax\n" + "".join(f"\\citation{{{key}}}\n" for key in citations)
        aux += "\\bibstyle{sn-nature}\n\\bibdata{bibliography}\n"
        (work / "references.aux").write_text(aux)
        result = subprocess.run(["bibtex", "references"], cwd=work, text=True,
                                capture_output=True, check=True)
        if "Warning--" in result.stdout:
            raise RuntimeError(result.stdout)
        bibliography = (work / "references.bbl").read_text()
    if re.findall(r"\\bibitem\{([^}]+)\}", bibliography) != citations:
        raise ValueError("Bibliography entries do not match citation order")
    if "???" in bibliography:
        raise ValueError("Unresolved bibliography placeholder")
    bibliography = bibliography.replace(r"\def\urlprefix{URL }", r"\def\urlprefix{}")
    generated = "% Generated by python3 manuscript/update_bibliography.py; edit bibliography.bib.\n"
    manuscript.write_text(before + BEGIN + "\n" + generated + bibliography + END + after)
    print(f"Embedded {len(citations)} references in {manuscript.name}")


if __name__ == "__main__":
    main()
